changed package
believerfenix/delivery_app pull request #2
Opened 2021-09-18 10:27 UTC by believerfenix

2021-10-05 17:55 UTC, EvgeniiKhudan requested changes

2021-10-05 17:55 UTC, EvgeniiKhudan commented on app/controllers/packages_controller.rb
>  class PackagesController < ApplicationController
можете удалить старые контроллеры, они вам больше не нужны

2021-10-05 17:55 UTC, EvgeniiKhudan commented on app/models/courier.rb
> +  has_many :packages, dependent: :restrict_with_error
эту связь можете смело удалять, в 5 US вы реализуете другую

2021-10-05 17:55 UTC, EvgeniiKhudan commented on app/views/couriers/partials/_create_package.html.erb
>  <h2>Add a package:</h2>
можете удалять старые вьюхи

2021-10-05 17:55 UTC, EvgeniiKhudan commented on db/migrate/20210720204119_create_packages.rb
> +      t.uuid :courier_id
вам не нужно это поле

2021-10-05 17:55 UTC, EvgeniiKhudan commented on db/migrate/20210720204119_create_packages.rb
> +      t.string :delivery_status, default: 'new'
не думаю что вам нужен этот default. Такого рода вещи имеют свойство часто меняться. А вот null: false не помешает для нескольких полей

2021-10-05 17:55 UTC, EvgeniiKhudan commented on app/models/package.rb
> +    self.tracking_number = "YA#{rand.to_s[2..9]}AA"
у вас есть ограничение на уникальность на уровне базы, перед сохранением вы должны проверять что сгенерили уникальный номер

2021-10-05 22:02 UTC, believerfenix commented on db/migrate/20210720204119_create_packages.rb
> +      t.string :delivery_status, default: 'new'
сделал так потому что в задании было указано: "Default delivery status of package should be new". default: 'new' можно просто убрать или же нужно этот пункт реализовать как-то по другому?

2021-10-09 08:09 UTC, EvgeniiKhudan commented on app/services/create_tracking_number_service.rb
> +    end
На втором занятии по ActiveRecord я объяснял опасность использования .all.each
Вы можете делать просто Package.exists?(tracking_number: tracking_number)
Вам здесь не нужен конструктор и инстанс переменная, можно же обойтись локальной

2021-10-09 08:12 UTC, EvgeniiKhudan commented on db/migrate/20210720204119_create_packages.rb
> +      t.string :delivery_status, default: 'new'
Инициацию начального статуса лучше вынести с базы на уровень приложения. Допустим у вас появится draft. В этом случае вам придется писать миграцию изменения default значения для колонки. В случае если это будет уровень приложения, достаточно добавить это значения в enum и поменять пару строк кода.

2021-10-15 13:56 UTC, EvgeniiKhudan requested changes
LGTM!

2021-10-17 09:32 UTC, merged